// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(libsilver_swiftFFI)
import libsilver_swiftFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_libsilver_swift_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_libsilver_swift_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        // TODO: This copies the buffer. Can we read directly from a
        // Rust buffer?
        self.init(bytes: rustBuffer.data!, count: Int(rustBuffer.len))
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous go the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_PANIC: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: nil)
}

private func rustCallWithError<T>(
    _ errorHandler: @escaping (RustBuffer) throws -> Error,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> Error)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> Error)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_PANIC:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
                throw CancellationError()

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

// Public interface members begin here.


fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}


public struct AesKey {
    public var key: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(key: Data) {
        self.key = key
    }
}


extension AesKey: Equatable, Hashable {
    public static func ==(lhs: AesKey, rhs: AesKey) -> Bool {
        if lhs.key != rhs.key {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(key)
    }
}


public struct FfiConverterTypeAesKey: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AesKey {
        return try AesKey(
            key: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: AesKey, into buf: inout [UInt8]) {
        FfiConverterData.write(value.key, into: &buf)
    }
}


public func FfiConverterTypeAesKey_lift(_ buf: RustBuffer) throws -> AesKey {
    return try FfiConverterTypeAesKey.lift(buf)
}

public func FfiConverterTypeAesKey_lower(_ value: AesKey) -> RustBuffer {
    return FfiConverterTypeAesKey.lower(value)
}


public struct Ed25519KeyPair {
    public var publicKey: Data
    public var privateKey: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(publicKey: Data, privateKey: Data) {
        self.publicKey = publicKey
        self.privateKey = privateKey
    }
}


extension Ed25519KeyPair: Equatable, Hashable {
    public static func ==(lhs: Ed25519KeyPair, rhs: Ed25519KeyPair) -> Bool {
        if lhs.publicKey != rhs.publicKey {
            return false
        }
        if lhs.privateKey != rhs.privateKey {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(publicKey)
        hasher.combine(privateKey)
    }
}


public struct FfiConverterTypeEd25519KeyPair: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Ed25519KeyPair {
        return try Ed25519KeyPair(
            publicKey: FfiConverterData.read(from: &buf), 
            privateKey: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: Ed25519KeyPair, into buf: inout [UInt8]) {
        FfiConverterData.write(value.publicKey, into: &buf)
        FfiConverterData.write(value.privateKey, into: &buf)
    }
}


public func FfiConverterTypeEd25519KeyPair_lift(_ buf: RustBuffer) throws -> Ed25519KeyPair {
    return try FfiConverterTypeEd25519KeyPair.lift(buf)
}

public func FfiConverterTypeEd25519KeyPair_lower(_ value: Ed25519KeyPair) -> RustBuffer {
    return FfiConverterTypeEd25519KeyPair.lower(value)
}


public struct EncryptionResult {
    public var ciphertext: Data
    public var nonce: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(ciphertext: Data, nonce: Data) {
        self.ciphertext = ciphertext
        self.nonce = nonce
    }
}


extension EncryptionResult: Equatable, Hashable {
    public static func ==(lhs: EncryptionResult, rhs: EncryptionResult) -> Bool {
        if lhs.ciphertext != rhs.ciphertext {
            return false
        }
        if lhs.nonce != rhs.nonce {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(ciphertext)
        hasher.combine(nonce)
    }
}


public struct FfiConverterTypeEncryptionResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EncryptionResult {
        return try EncryptionResult(
            ciphertext: FfiConverterData.read(from: &buf), 
            nonce: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: EncryptionResult, into buf: inout [UInt8]) {
        FfiConverterData.write(value.ciphertext, into: &buf)
        FfiConverterData.write(value.nonce, into: &buf)
    }
}


public func FfiConverterTypeEncryptionResult_lift(_ buf: RustBuffer) throws -> EncryptionResult {
    return try FfiConverterTypeEncryptionResult.lift(buf)
}

public func FfiConverterTypeEncryptionResult_lower(_ value: EncryptionResult) -> RustBuffer {
    return FfiConverterTypeEncryptionResult.lower(value)
}

public enum CryptoError {

    
    
    // Simple error enums only carry a message
    case InvalidInput(message: String)
    
    // Simple error enums only carry a message
    case CryptographicError(message: String)
    
    // Simple error enums only carry a message
    case KeyGenerationError(message: String)
    
    // Simple error enums only carry a message
    case EncryptionError(message: String)
    
    // Simple error enums only carry a message
    case DecryptionError(message: String)
    
    // Simple error enums only carry a message
    case SignatureError(message: String)
    
    // Simple error enums only carry a message
    case VerificationError(message: String)
    
    // Simple error enums only carry a message
    case HashError(message: String)
    
    // Simple error enums only carry a message
    case KdfError(message: String)
    
    // Simple error enums only carry a message
    case RandomError(message: String)
    

    fileprivate static func uniffiErrorHandler(_ error: RustBuffer) throws -> Error {
        return try FfiConverterTypeCryptoError.lift(error)
    }
}


public struct FfiConverterTypeCryptoError: FfiConverterRustBuffer {
    typealias SwiftType = CryptoError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CryptoError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InvalidInput(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .CryptographicError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .KeyGenerationError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .EncryptionError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .DecryptionError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 6: return .SignatureError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 7: return .VerificationError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 8: return .HashError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 9: return .KdfError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 10: return .RandomError(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CryptoError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .InvalidInput(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .CryptographicError(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .KeyGenerationError(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))
        case .EncryptionError(_ /* message is ignored*/):
            writeInt(&buf, Int32(4))
        case .DecryptionError(_ /* message is ignored*/):
            writeInt(&buf, Int32(5))
        case .SignatureError(_ /* message is ignored*/):
            writeInt(&buf, Int32(6))
        case .VerificationError(_ /* message is ignored*/):
            writeInt(&buf, Int32(7))
        case .HashError(_ /* message is ignored*/):
            writeInt(&buf, Int32(8))
        case .KdfError(_ /* message is ignored*/):
            writeInt(&buf, Int32(9))
        case .RandomError(_ /* message is ignored*/):
            writeInt(&buf, Int32(10))

        
        }
    }
}


extension CryptoError: Equatable, Hashable {}

extension CryptoError: Error { }

public func decryptAes(ciphertext: Data, nonce: Data, key: AesKey) throws -> Data {
    return try  FfiConverterData.lift(
        try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_libsilver_swift_fn_func_decrypt_aes(
        FfiConverterData.lower(ciphertext),
        FfiConverterData.lower(nonce),
        FfiConverterTypeAesKey.lower(key),$0)
}
    )
}

public func encryptAes(plaintext: Data, key: AesKey) throws -> EncryptionResult {
    return try  FfiConverterTypeEncryptionResult.lift(
        try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_libsilver_swift_fn_func_encrypt_aes(
        FfiConverterData.lower(plaintext),
        FfiConverterTypeAesKey.lower(key),$0)
}
    )
}

public func generateAesKey() throws -> AesKey {
    return try  FfiConverterTypeAesKey.lift(
        try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_libsilver_swift_fn_func_generate_aes_key($0)
}
    )
}

public func generateEd25519Keypair() throws -> Ed25519KeyPair {
    return try  FfiConverterTypeEd25519KeyPair.lift(
        try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_libsilver_swift_fn_func_generate_ed25519_keypair($0)
}
    )
}

public func generateRandomBytes(length: UInt32) throws -> Data {
    return try  FfiConverterData.lift(
        try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_libsilver_swift_fn_func_generate_random_bytes(
        FfiConverterUInt32.lower(length),$0)
}
    )
}

public func getVersion()  -> String {
    return try!  FfiConverterString.lift(
        try! rustCall() {
    uniffi_libsilver_swift_fn_func_get_version($0)
}
    )
}

public func initialize()  {
    try! rustCall() {
    uniffi_libsilver_swift_fn_func_initialize($0)
}
}



public func sha256(data: Data) throws -> Data {
    return try  FfiConverterData.lift(
        try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_libsilver_swift_fn_func_sha256(
        FfiConverterData.lower(data),$0)
}
    )
}

public func sha256Hex(data: Data) throws -> String {
    return try  FfiConverterString.lift(
        try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_libsilver_swift_fn_func_sha256_hex(
        FfiConverterData.lower(data),$0)
}
    )
}

public func signEd25519(message: Data, privateKey: Data) throws -> Data {
    return try  FfiConverterData.lift(
        try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_libsilver_swift_fn_func_sign_ed25519(
        FfiConverterData.lower(message),
        FfiConverterData.lower(privateKey),$0)
}
    )
}

public func verifyEd25519(message: Data, signature: Data, publicKey: Data) throws -> Bool {
    return try  FfiConverterBool.lift(
        try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_libsilver_swift_fn_func_verify_ed25519(
        FfiConverterData.lower(message),
        FfiConverterData.lower(signature),
        FfiConverterData.lower(publicKey),$0)
}
    )
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variables to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 24
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_libsilver_swift_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_libsilver_swift_checksum_func_decrypt_aes() != 3911) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libsilver_swift_checksum_func_encrypt_aes() != 16483) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libsilver_swift_checksum_func_generate_aes_key() != 18294) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libsilver_swift_checksum_func_generate_ed25519_keypair() != 48333) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libsilver_swift_checksum_func_generate_random_bytes() != 62531) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libsilver_swift_checksum_func_get_version() != 44066) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libsilver_swift_checksum_func_initialize() != 61473) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libsilver_swift_checksum_func_sha256() != 39689) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libsilver_swift_checksum_func_sha256_hex() != 46408) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libsilver_swift_checksum_func_sign_ed25519() != 33426) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libsilver_swift_checksum_func_verify_ed25519() != 61865) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}